databases:
  - name: loop-db
    plan: free
    databaseName: loop_playlist
    user: loop_user

services:
  - type: web
    name: loop-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loop-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
